title: Robert E. Hatem
email: rhatem@uchicago.edu
description: > # this means to ignore newlines until "baseurl:"
  Now I can pontificate.

# social links
# twitter_username: your-twitter-handle
github_username:  hatemr
linkedin_username: robert-e-hatem 

base-url: https://hatemr.github.io/

show_excerpts: false # true # set to false to remove excerpts on the homepage

theme: minima #jekyll-theme-minimal

markdown: kramdown

plugins:
  - jekyll-feed
